const express = require('express');
const router = express.Router();
const cartController = require('../controllers/CartController');
router.post('/addcart/:id',cartController.addCart);
router.post('/addmealcart/:id',cartController.addMealCart);
router.post('/removecartitem/:id',cartController.removeCartItem);
router.post('/removemealcart/:id',cartController.removeMealCart);
router.post('/getcartitem',cartController.getCartItem);
router.post('/checkcoupon/:id',cartController.checkCoupon);
router.post('/getmealcart',cartController.getMealCart);
router.post('/removebeverageitem',cartController.removeBeverageItem);
module.exports = router;